version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  postgres:
